# Generated by ExperimentSpec compiler; do not edit generated output.
# schema_version: 1.0
# experiment: LJ NVE/NVT comparison
# ensemble: {{ENSEMBLE_UPPER}}
# spec_sha256: {{SPEC_SHA256}}

clear
units           {{UNITS}}
dimension       {{DIMENSION}}
boundary        {{BOUNDARY}}
atom_style      atomic

variable        temperature equal {{TEMPERATURE}}
variable        density equal {{DENSITY}}
variable        cells equal {{CELLS}}
variable        seed equal {{SEED}}
variable        equil_steps equal {{EQUILIBRATION_STEPS}}
variable        prod_steps equal {{PRODUCTION_STEPS}}
variable        thermostat_damping equal {{THERMOSTAT_DAMPING}}

lattice         {{LATTICE}} ${density}
region          box block 0 ${cells} 0 ${cells} 0 ${cells} units lattice
create_box      1 box
create_atoms    1 box
mass            1 {{MASS}}

pair_style      {{PAIR_STYLE}} {{CUTOFF}}
pair_coeff      1 1 {{EPSILON}} {{SIGMA}} {{CUTOFF}}
pair_modify     shift {{SHIFT}}
neighbor        {{NEIGHBOR_SKIN}} bin
neigh_modify    delay 0 every 1 check yes

timestep        {{TIMESTEP}}
velocity        all create ${temperature} ${seed} mom yes rot no dist gaussian

thermo          {{THERMO_INTERVAL}}
thermo_style    custom step atoms temp press pe ke etotal density
thermo_modify   flush yes

# Both compiled cases use exactly the same deterministic equilibration protocol.
fix             preparation all nvt temp ${temperature} ${temperature} ${thermostat_damping}
run             ${equil_steps}
unfix           preparation
velocity        all scale ${temperature}

reset_timestep  0
{{PRODUCTION_FIX}}

variable        sample_step equal step
variable        sample_temp equal temp
variable        sample_press equal press
variable        sample_pe equal pe
variable        sample_ke equal ke
variable        sample_etotal equal etotal
variable        sample_atoms equal atoms

fix             observables all print {{THERMO_INTERVAL}} "${sample_step},${sample_temp},${sample_press},${sample_pe},${sample_ke},${sample_etotal},${sample_atoms}" file thermo.csv screen no title "step,temp,pressure,pe,ke,etotal,atoms"
dump            trajectory all custom {{TRAJECTORY_INTERVAL}} trajectory.lammpstrj id type x y z vx vy vz
{{SORT_ATOMS}}

run             ${prod_steps}
write_data      final.data
